[book]
title = "ğŸ”° Manual de ReferÃªncia do Programador Neob"
description = "A Linguagem de ProgramaÃ§Ã£o Neob"
language = "pt"
src = "src"
authors = [
  "Raul Bras",
  "ContribuiÃ§Ãµes da Comunidade Neob"
]

[output.html]
theme = "theme"
